#!/usr/bin/python3
"""
Sends a request to the specified server in order to receive the available
files to download from it.
"""

from datetime import datetime
from lib.cli_parse import parse_args_list
from lib.rdt_interface import recvfrom_fixed_addr, sendto_fixed_addr
from lib.rdt_selection import create_rdt
from lib.socket_udp import Socket, SocketTimeout
from lib.logger import logger
from lib.misc import get_size_readable
import lib.protocol as prt


def list_files(logger_level, ADDR, PORT, ASC, SORT_KEY):
    logger.setLevel(logger_level)

    skt = Socket()
    addr = (ADDR, PORT)
    rdt = create_rdt(sendto_fixed_addr(skt, addr), recvfrom_fixed_addr(skt))

    prt.listfiles_request(rdt)

    files_list = prt.recv_list(rdt)

    if not files_list:
        print("No hay archivos disponibles en el servidor.")
        return 0

    sorted_by = {
        "name": 0,
        "size": 1,
        "date": 2
    }

    print(f"Archivos disponibles ({len(files_list)}):")

    files_list.sort(reverse=not ASC,
                    key=lambda x: x[sorted_by[SORT_KEY]])
    for filename, size, mtime in files_list:
        mtime = datetime.fromtimestamp(mtime).strftime('%d-%b-%Y (%H:%M:%S)')
        print(f"> [{mtime}] {filename} - {get_size_readable(size)}")


def main(args):
    list_files(args.level, args.ADDR, args.PORT, args.ASC, args.SORT_KEY)
    return 0


if __name__ == "__main__":
    args = parse_args_list()
    try:
        main(args)
    except KeyboardInterrupt:
        print()
        logger.fatal("Program was ended by KeyboardInterrupt")
    except SocketTimeout:
        logger.fatal("Socket error: Connection timed-out.")
    except BaseException:
        logger.exception("Unexpected error during execution:")
        exit(1)
