#!/usr/bin/env python
"""
Sends a request to the specified server in order to receive the available
files to download from it.
"""

from datetime import datetime
from lib.cli_parse import parse_args_list
from lib.rdt_interface import recvfrom_fixed_addr, sendto_fixed_addr
from lib.rdt_selection import create_rdt
from lib.socket_udp import Socket
from lib.logger import logger
from lib.formatters import get_size_readable
import lib.protocol as prt


def main(args):
    logger.setLevel(args.level)

    skt = Socket()
    addr = (args.ADDR, args.PORT)
    rdt = create_rdt(sendto_fixed_addr(skt, addr), recvfrom_fixed_addr(skt))

    prt.send_opcode(rdt, prt.LIST_FILES_OP)
    s = prt.recv_status(rdt)
    if s:
        raise RuntimeError(prt.get_error_msg(s))

    files_list = prt.recv_list(rdt)

    if not files_list:
        print("No hay archivos disponibles en el servidor.")
        return 0

    sorted_by = {
        "name": 0,
        "size": 1,
        "date": 2
    }

    print(f"Archivos disponibles ({len(files_list)}):")

    files_list.sort(reverse=not args.ASC,
                    key=lambda x: x[sorted_by[args.SORT_KEY]])
    for filename, size, mtime in files_list:
        mtime = datetime.fromtimestamp(mtime).strftime('%d-%b-%Y (%H:%M:%S)')
        print(f"> [{mtime}] {filename} - {get_size_readable(size)}")

    return 0


if __name__ == "__main__":
    args = parse_args_list()
    try:
        main(args)
    except BaseException as e:
        raise e
        logger.fatal(e)
        exit(1)
