#!/usr/bin/python3
"""
Starts a server on address and port received, and listens to requests
from clients.
"""

from os import chdir, mkdir
from argparse import ArgumentParser
from lib.socket_udp import Socket, SocketTimeout
from lib.receiver import Receiver
from lib.logger import logger, DEBUG_LEVEL, INFO_LEVEL, FATAL_LEVEL
from lib.stats import print_stats
from __main__ import __doc__ as description, __file__
from lib.constants import DEFAULT_ADDR, DEFAULT_PORT


DEFAULT_DIRPATH = "files"


def parse_args():
    """
    Parse args using `argparse` in order to fullfil requirements.
    """

    parser = ArgumentParser(description=description,
                            prog=__file__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-v", "--verbose", action="store_const",
                       dest="level", const=DEBUG_LEVEL, default=INFO_LEVEL,
                       help="Increase output verbosity")
    group.add_argument("-q", "--quiet", action="store_const",
                       dest="level", const=FATAL_LEVEL,
                       help="Decrease output verbosity")
    parser.add_argument("-H", "--host", dest="ADDR", type=str,
                        default=DEFAULT_ADDR, help="service IP address")
    parser.add_argument("-p", "--port", dest="PORT", type=int,
                        default=DEFAULT_PORT, help="service port")
    parser.add_argument("-s", "--storage", dest="DIRPATH", type=str,
                        default=DEFAULT_DIRPATH, help="storage dir path")

    return parser.parse_args()


def start_server(logger_level, DIRPATH, ADDR, PORT):
    logger.setLevel(logger_level)

    try:
        chdir(DIRPATH)
    except FileNotFoundError:
        if DIRPATH == DEFAULT_DIRPATH:
            mkdir(DIRPATH)
            chdir(DIRPATH)
        else:
            logger.fatal(f'Invalid directory: {DIRPATH}')
            exit(1)

    skt = Socket()
    skt.bind(ADDR, PORT)

    receiver = Receiver(skt)
    logger.info(f"Server started. Listening on port {PORT}.")

    print("Enter `s` to print stats, or `q` to exit.")
    while True:
        try:
            option = input()
            if option == 's':
                print_stats()
            elif option == 'q':
                raise EOFError()
            print("Enter `s` to print stats, or `q` to exit.")
        except (EOFError, KeyboardInterrupt):
            try:
                receiver.stop()
            except RuntimeWarning:
                logger.warning("Not every handler is done, it could "
                               "take a few seconds to end the connections.")
                option = input(" -> Force stop? [y/n]")
                if option in {'s', 'S', 'y', 'Y', 'yes'}:
                    receiver.stop(True)
            break

    logger.info("Server closed.")
    return


def main(args):
    start_server(args.level, args.DIRPATH, args.ADDR, args.PORT)

    if args.level < FATAL_LEVEL:
        print_stats()
    return 0


if __name__ == "__main__":
    args = parse_args()
    try:
        main(args)
    except SocketTimeout:
        logger.fatal("Socket error: Connection timed-out.")
    except BaseException:
        logger.exception("Unexpected error during execution:")
        exit(1)
