#!/usr/bin/python3
"""
Sends a request to the specified server in order to upload the specified
file and make it available to download.
"""

from os import path

# Lib
from lib.cli_parse import parse_args_upload
from lib.rdt_interface import recvfrom_fixed_addr, sendto_fixed_addr
from lib.rdt_selection import create_rdt
from lib.socket_udp import Socket
from lib.logger import logger
from lib.misc import filesize
import lib.protocol as prt


def main(args):
    logger.setLevel(args.level)

    if not path.isfile(args.FILEPATH):
        raise FileNotFoundError(f"File not found: {args.FILEPATH}")

    skt = Socket()
    addr = (args.ADDR, args.PORT)
    rdt = create_rdt(sendto_fixed_addr(skt, addr), recvfrom_fixed_addr(skt))

    prt.upload_request(rdt, args.FILENAME, filesize(args.FILEPATH))

    logger.info("Uploading file...")

    with open(args.FILEPATH, 'rb') as f:
        prt.send_file(rdt, f, True)

    logger.info("File uploaded.")

    return 0


if __name__ == "__main__":
    args = parse_args_upload()
    try:
        main(args)
    except BaseException as e:
        raise e
        logger.fatal(e)
        exit(1)
