#!/usr/bin/python3
"""
Sends a request to the specified server in order to upload the specified
file and make it available to download.
"""

from os import path

# Lib
from lib.cli_parse import parse_args_upload
from lib.rdt_interface import recvfrom_fixed_addr, sendto_fixed_addr
from lib.rdt_selection import create_rdt
from lib.socket_udp import Socket, SocketTimeout
from lib.logger import logger
from lib.misc import filesize
import lib.protocol as prt


def upload_file(logger_level, FILEPATH, ADDR, PORT, FILENAME):
    logger.setLevel(logger_level)

    if not path.isfile(FILEPATH):
        raise FileNotFoundError(f"File not found: {FILEPATH}")

    skt = Socket()
    addr = (ADDR, PORT)
    rdt = create_rdt(sendto_fixed_addr(skt, addr), recvfrom_fixed_addr(skt))

    prt.upload_request(rdt, FILENAME, filesize(FILEPATH))

    logger.info("Uploading file...")

    with open(FILEPATH, 'rb') as f:
        prt.send_file(rdt, f, True)

    logger.info("File uploaded.")


def main(args):
    upload_file(args.level, args.FILEPATH, args.ADDR, args.PORT, args.FILENAME)

    return 0


if __name__ == "__main__":
    args = parse_args_upload()
    try:
        main(args)
    except KeyboardInterrupt:
        print()
        logger.fatal("Program was ended by KeyboardInterrupt")
    except SocketTimeout:
        logger.fatal("Socket error: Connection timed-out.")
    except BaseException:
        logger.exception("Unexpected error during execution:")
        exit(1)
